### ISSUE TITLE
places().length for two cities name with spaces equal to 1

### ISSUE THREAD

**Issue by rheza** [nlp-compromise/nlp_compromise#230]
Hi, 

I think i found a new issues.

So two cities name like "stockholm warsaw" equal to 1.
if it's two cities name like "stockholm to warsaw" it will be equal to 2.
Why the "to" needed, nlp was not human, the result should be the same like the second example.

thanks 

my current fix for now,

```javascript
var foundTo = text.search("to");
console.log("FOUND TO"+foundTo);
     if(foundTo == -1){
          text = text.replace(/ /," to ");
       }
```
it will replace the first space with "to".

**Comment by spencermountain** [comment]
hi Rheza, oh, this is a good point. "CityA to CityB" should be two places for sure.
let me fix it.

**Comment by rheza** [comment]
Just to make sure you understand. The "CityA  CityB"  should equal to 2 like on "CityA to CityB".

So,
"CityA CityB" length = 2
"CityA to CityB" length = 2

Thanks

**Comment by rheza** [comment]
Any updates on this ?, Really hope this one fixed quickly. :D

**Comment by spencermountain** [comment]
yeah, this may be fixed in 6.4.0 actually. 
check it out? I'm swamped this week.

**Comment by rheza** [comment]
@spencermountain Thanks man. looking forward to it.

**Comment by silentrob** [comment]
@rheza at the expense of sounding a little brash, you realize this is an open source project. @spencermountain does not work for you. If this is an issue that is blocking you, you are able to submit a pull request directly or pay someone to patch it or help maintain it. 

Please show a little respect to all the people who work tirelessly on these projects.

**Comment by rheza** [comment]
@silentrob
I know it's open source project and I know nobody works for me on this project. I was just asking status. Sorry if it's sound too much. I wish I understand how to solve this. Let me learn first. Hopefully not that hard. Thank you.

**Comment by spencermountain** [comment]
hey Rheza, think I got this fixed in `6.4.4`. 
* `stockholm warsaw` -> 2 terms
* `stockholm to warsaw` -> 3 terms
it's not perfect, `"smallCity1 smallCity2"` may still lump together, if it's not in our city list.
cheers!

**Comment by rheza** [comment]
Yeah, Looks like it still failing on certain circumstances, especially places added with lexicon. Will post the full log if i have time. Thanks
